#!/usr/bin/env bash
## Moves all `*.md` files in _drafts/ -> _posts/ with todays date prepended to the file name

set -eu
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

today="$(date +%Y-%m-%d)"

cd "$dir/_drafts"
for draft in *.md; do
  echo "_drafts/$draft -> _posts/$today-$draft"
  mv "$draft" "../_posts/$today-$draft"
done
